### ISSUE TITLE
[FEATURE REQUEST] Please add batch mode

### ISSUE THREAD

**Issue by Jimmm** [XyLe-GBP/ATRACTool-Reloaded#1]
Hi XyLe-GBP,

I want to convert a lot of files to at3, but doing so 1 by 1 is tooo slow. If I drag and drop many files, I got an error:
![image](https://user-images.githubusercontent.com/960136/156385609-a03a735f-1de6-43d4-b5b2-c2a53ef0a244.png)

**Comment by XyLe-GBP** [comment]
Fixed an error when encoding multiple files in an update.
If the problem still exists, please write here.

**Comment by Jimmm** [comment]
It is ok now, thanks!
