### ISSUE TITLE
Psp_at3tool v3.0.0

### ISSUE THREAD

**Issue by jgoulet921** [XyLe-GBP/ATRACTool-Reloaded#11]
Not a feature request per say, 

I see you ship the tool with v2.0.0 and as I have the updated version I wondered if you'd like me to send it to you?
I also have the Linux binary as well though you have to export the LD path and ideally create a symlink to the 1.0 version of the accompanying library it expects.

Its not a major update but nice to have nonetheless.

I think I'll just include them here.

[at3tool.zip](https://github.com/XyLe-GBP/ATRACTool-Reloaded/files/13773236/at3tool.zip)

**Comment by XyLe-GBP** [comment]
@jgoulet921
It was a blind spot that v3.0 existed.
I will incorporate this into the next update.
Thanks for providing the binary :)

**Comment by jgoulet921** [comment]
no problem I'll close the issue.
