### ISSUE TITLE
[REQ] Please add PSP 44.1kHz support

### ISSUE THREAD

**Issue by Jimmm** [XyLe-GBP/ATRACTool-Reloaded#3]
I found 4 atrac encoders here:
https://www.psx-place.com/resources/at9-at3-converter.566/update?update=1115
They are for PSP, PS3, ViTA and PS4.
![image](https://user-images.githubusercontent.com/960136/157121666-b986e0f7-6591-4819-b183-f7be0d918b3d.png)

PSP needs 44.1kHz at3, your app supports PS3 at3 with 48kHz only.

**Comment by XyLe-GBP** [comment]
Thank you for your report. We will incorporate it into an upcoming update.
Please be patient.

**Comment by XyLe-GBP** [comment]
Updated to support ATRAC conversion for PSP and PS4.
If the problem still exists, please write here.

**Comment by Jimmm** [comment]
Just tested PSP, it works! Thanks a lot!
