### ISSUE TITLE
Header Format for .at3 plus (question)

### ISSUE THREAD

**Issue by BAD-AL** [XyLe-GBP/ATRACTool-Reloaded#4]
Do you know where the header format for at3 and at3 plus is specified?
I cannot seem to find it.
(I do realize you just call an .exe to convert the files in this program, just hoping to find the header format specification )

**Comment by XyLe-GBP** [comment]
We are aware of this, but we do not plan to support such applications at this time.
Except for PSP, PS3, PSV, and PS4, we do not support them at this time.

**Comment by BAD-AL** [comment]
I think you misunderstood the question.

I'm looking for info on the altrac3 plus audio header, not asking for any code changes or features.

Like for info on .wav headers I can refer to:
 * http://soundfile.sapp.org/doc/WaveFormat/
 
and for the .vag audio format (for ps2) I can refer to:
  * https://wiki.xentax.com/index.php/VAG_Audio

Do you know anywhere that a specification exists for altrac3/altrac3plus?

**Comment by XyLe-GBP** [comment]
If [this](https://datatracker.ietf.org/doc/html/rfc5584) is not the material you are looking for, I am not sure I can help you.
